// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEoJk6-400wwrzKnr5vWgc4USbix9F_E',
    appId: '1:369745410558:web:243be1df1b88717eef28af',
    messagingSenderId: '369745410558',
    projectId: 'connectly-a388f',
    authDomain: 'connectly-a388f.firebaseapp.com',
    storageBucket: 'connectly-a388f.firebasestorage.app',
    measurementId: 'G-3JHY5QNKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PSHlOzXZ-EbRKqzHqHFauabWTxHyWI0',
    appId: '1:369745410558:android:562f6ec2b18167b1ef28af',
    messagingSenderId: '369745410558',
    projectId: 'connectly-a388f',
    storageBucket: 'connectly-a388f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6ULDPZfBGk0gwL1mmFvCJyLb0JZsxFs',
    appId: '1:369745410558:ios:9c5c54c843ca1447ef28af',
    messagingSenderId: '369745410558',
    projectId: 'connectly-a388f',
    storageBucket: 'connectly-a388f.firebasestorage.app',
    iosBundleId: 'com.example.connectlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_6ULDPZfBGk0gwL1mmFvCJyLb0JZsxFs',
    appId: '1:369745410558:ios:9c5c54c843ca1447ef28af',
    messagingSenderId: '369745410558',
    projectId: 'connectly-a388f',
    storageBucket: 'connectly-a388f.firebasestorage.app',
    iosBundleId: 'com.example.connectlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGEoJk6-400wwrzKnr5vWgc4USbix9F_E',
    appId: '1:369745410558:web:06554ac05a8952ebef28af',
    messagingSenderId: '369745410558',
    projectId: 'connectly-a388f',
    authDomain: 'connectly-a388f.firebaseapp.com',
    storageBucket: 'connectly-a388f.firebasestorage.app',
    measurementId: 'G-R2X74DC7E7',
  );
}
